- hosts: all
  tasks:
    - shell:
        cmd: |
          set -e
          set -x
          if [ "{{ puppet_gem_version }}" != "latest" ]; then
            if [ "{{ puppet_gem_version }}" == "5.5" ]; then
              # Pin to 5.5.6. See PUP-9270 and PUP-9271
              export PUPPET_GEM_VERSION='{{ puppet_gem_version }}.6'
            else
              export PUPPET_GEM_VERSION='~> {{ puppet_gem_version }}.0'
            fi
          fi
          ./run_unit_tests.sh
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

